spring:
  datasource:
    url: jdbc:h2:mem:batchdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      names: accountJob

  sql:
    init:
      mode: always
